### ISSUE TITLE
update to latest triangle package 

### ISSUE THREAD

**Issue by pjebs** [rocketlaunchr/showerglass#1]
The moment the bug is fixed and new version is tagged, modify the mod file. Also tag `v1.0.0`

https://github.com/esimov/triangle/issues/23

**Comment by esimov** [comment]
The bug is fixed now and a new release is coming soon. This will embrace a completely new architectural overview and will contains new additional options for further adjusting the generated outputs. I realized that API does not stands up very well in terms of segregation of responsibilities because for example the publicly exposed Draw method should not be responsible of encoding the results into an image file. Anyway all the related changes will be documented.
